# Generated by Django 3.2.5 on 2021-08-11 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='State',
            new_name='state',
        ),
    ]
