# Generated by Django 3.2.5 on 2021-08-18 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_rename_state_address_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='image',
            field=models.FileField(blank=True, default='customer/customer/images/default.jpg', help_text='customer image', null=True, upload_to='customer/customer/images/', verbose_name='Customer image'),
        ),
    ]
