# Generated by Django 3.2.5 on 2021-08-09 05:50

from django.db import migrations, models
import django.db.models.deletion
import product.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delete_time_stamp', models.DateTimeField(blank=True, default=None, help_text='Time of delete', null=True, verbose_name='Deleted Time Stamp')),
                ('is_deleted', models.BooleanField(default=False, help_text='Is delete or not?', verbose_name='Is Deleted')),
                ('create_time_stamp', models.DateTimeField(auto_now_add=True, help_text='Time of create', verbose_name='Create Time Stamp')),
                ('modify_time_stamp', models.DateTimeField(auto_now=True, help_text='Time of modify', verbose_name='Modify Time Stamp')),
                ('name', models.CharField(help_text='Enter the brand name', max_length=30, verbose_name='brand name')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delete_time_stamp', models.DateTimeField(blank=True, default=None, help_text='Time of delete', null=True, verbose_name='Deleted Time Stamp')),
                ('is_deleted', models.BooleanField(default=False, help_text='Is delete or not?', verbose_name='Is Deleted')),
                ('create_time_stamp', models.DateTimeField(auto_now_add=True, help_text='Time of create', verbose_name='Create Time Stamp')),
                ('modify_time_stamp', models.DateTimeField(auto_now=True, help_text='Time of modify', verbose_name='Modify Time Stamp')),
                ('name', models.CharField(help_text='Category Name', max_length=50, verbose_name='Name')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.category')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delete_time_stamp', models.DateTimeField(blank=True, default=None, help_text='Time of delete', null=True, verbose_name='Deleted Time Stamp')),
                ('is_deleted', models.BooleanField(default=False, help_text='Is delete or not?', verbose_name='Is Deleted')),
                ('create_time_stamp', models.DateTimeField(auto_now_add=True, help_text='Time of create', verbose_name='Create Time Stamp')),
                ('modify_time_stamp', models.DateTimeField(auto_now=True, help_text='Time of modify', verbose_name='Modify Time Stamp')),
                ('is_percent', models.BooleanField(default=False, help_text='Do you want to enter a percentage?', verbose_name='Is Percent?')),
                ('price', models.IntegerField(default=0, help_text='Enter the discount price', validators=[product.validators.price_validator], verbose_name='Discount Price')),
                ('percent', models.FloatField(default=0, help_text='Enter the discount percent', validators=[product.validators.percent_validator], verbose_name='Discount Percent')),
                ('max', models.IntegerField(blank=True, help_text='Enter the max discount price', null=True, validators=[product.validators.price_validator], verbose_name='Max Discount Price')),
                ('expire_date_time', models.DateTimeField(help_text='Enter the expire date', verbose_name='Expire Date')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delete_time_stamp', models.DateTimeField(blank=True, default=None, help_text='Time of delete', null=True, verbose_name='Deleted Time Stamp')),
                ('is_deleted', models.BooleanField(default=False, help_text='Is delete or not?', verbose_name='Is Deleted')),
                ('create_time_stamp', models.DateTimeField(auto_now_add=True, help_text='Time of create', verbose_name='Create Time Stamp')),
                ('modify_time_stamp', models.DateTimeField(auto_now=True, help_text='Time of modify', verbose_name='Modify Time Stamp')),
                ('name', models.CharField(help_text='Enter the Menu items name', max_length=30, verbose_name='menu item name')),
                ('description', models.TextField(blank=True, help_text='Enter the menu item description', null=True, verbose_name='menu item description')),
                ('brand', models.ForeignKey(blank=True, help_text='Choose the menu item brand', null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.brand', verbose_name='menu item brand')),
                ('category', models.ForeignKey(help_text='Choose the menu item stock', on_delete=django.db.models.deletion.CASCADE, to='product.category', verbose_name='menu item category')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Specification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delete_time_stamp', models.DateTimeField(blank=True, default=None, help_text='Time of delete', null=True, verbose_name='Deleted Time Stamp')),
                ('is_deleted', models.BooleanField(default=False, help_text='Is delete or not?', verbose_name='Is Deleted')),
                ('create_time_stamp', models.DateTimeField(auto_now_add=True, help_text='Time of create', verbose_name='Create Time Stamp')),
                ('modify_time_stamp', models.DateTimeField(auto_now=True, help_text='Time of modify', verbose_name='Modify Time Stamp')),
                ('name', models.CharField(help_text='Enter the Specification name', max_length=200, verbose_name='Specification name')),
                ('value', models.CharField(help_text='Enter the Specification value', max_length=200, verbose_name='Specification Value')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VariableSpecification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delete_time_stamp', models.DateTimeField(blank=True, default=None, help_text='Time of delete', null=True, verbose_name='Deleted Time Stamp')),
                ('is_deleted', models.BooleanField(default=False, help_text='Is delete or not?', verbose_name='Is Deleted')),
                ('create_time_stamp', models.DateTimeField(auto_now_add=True, help_text='Time of create', verbose_name='Create Time Stamp')),
                ('modify_time_stamp', models.DateTimeField(auto_now=True, help_text='Time of modify', verbose_name='Modify Time Stamp')),
                ('name', models.CharField(help_text='Enter the Specification name', max_length=200, verbose_name='Specification name')),
                ('value', models.CharField(help_text='Enter the Specification value', max_length=200, verbose_name='Specification Value')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OffCode',
            fields=[
                ('discount_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='product.discount')),
                ('code', models.CharField(help_text='Enter the off code', max_length=14, validators=[product.validators.off_code_validator], verbose_name='Off Code')),
            ],
            options={
                'abstract': False,
            },
            bases=('product.discount',),
        ),
        migrations.CreateModel(
            name='MenuItemVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delete_time_stamp', models.DateTimeField(blank=True, default=None, help_text='Time of delete', null=True, verbose_name='Deleted Time Stamp')),
                ('is_deleted', models.BooleanField(default=False, help_text='Is delete or not?', verbose_name='Is Deleted')),
                ('create_time_stamp', models.DateTimeField(auto_now_add=True, help_text='Time of create', verbose_name='Create Time Stamp')),
                ('modify_time_stamp', models.DateTimeField(auto_now=True, help_text='Time of modify', verbose_name='Modify Time Stamp')),
                ('price', models.IntegerField(help_text='Enter the menu item price', validators=[product.validators.price_validator], verbose_name='menu item price')),
                ('count', models.IntegerField(default=0, help_text='Enter the menu item stock', validators=[product.validators.price_validator], verbose_name='menu item stock')),
                ('discount', models.ForeignKey(blank=True, help_text='Enter the menu item discount', null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.discount', verbose_name='menu item discount')),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.menuitem')),
                ('variable_specifications', models.ManyToManyField(related_name='menu_item_variants', to='product.VariableSpecification')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='menuitem',
            name='specifications',
            field=models.ManyToManyField(related_name='menu_items', to='product.Specification'),
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delete_time_stamp', models.DateTimeField(blank=True, default=None, help_text='Time of delete', null=True, verbose_name='Deleted Time Stamp')),
                ('is_deleted', models.BooleanField(default=False, help_text='Is delete or not?', verbose_name='Is Deleted')),
                ('create_time_stamp', models.DateTimeField(auto_now_add=True, help_text='Time of create', verbose_name='Create Time Stamp')),
                ('modify_time_stamp', models.DateTimeField(auto_now=True, help_text='Time of modify', verbose_name='Modify Time Stamp')),
                ('image', models.FileField(help_text='Enter your image', upload_to='product/menu_items/images/', verbose_name='menu item image')),
                ('menu_item', models.ForeignKey(help_text='Enter the menu item for this image', on_delete=django.db.models.deletion.CASCADE, to='product.menuitem', verbose_name='menu item for this image')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
