# Generated by Django 3.2.5 on 2021-08-01 13:55

from django.db import migrations, models
import product.validators


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delete_time_stamp', models.DateTimeField(blank=True, default=None, help_text='Time of delete', null=True, verbose_name='Deleted Time Stamp')),
                ('is_deleted', models.BooleanField(default=False, help_text='Is delete or not?', verbose_name='Is Deleted')),
                ('create_time_stamp', models.DateTimeField(auto_now_add=True, help_text='Time of create', verbose_name='Create Time Stamp')),
                ('modify_time_stamp', models.DateTimeField(auto_now=True, help_text='Time of modify', verbose_name='Modify Time Stamp')),
                ('is_percent', models.BooleanField(default=False, help_text='Do you want to enter a percentage?', verbose_name='Is Percent?')),
                ('price', models.IntegerField(help_text='Enter the discount price', validators=[product.validators.price_validator], verbose_name='Discount Price')),
                ('percent', models.FloatField(help_text='Enter the discount percent', validators=[product.validators.percent_validator], verbose_name='Discount Percent')),
                ('max', models.IntegerField(help_text='Enter the max discount price', validators=[product.validators.price_validator], verbose_name='Max Discount Price')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
