# Generated by Django 3.2.5 on 2021-08-19 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_sub_category',
            field=models.BooleanField(default=False, help_text='Is sub category? or main?', verbose_name='Is sub category?'),
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='category',
        ),
        migrations.AddField(
            model_name='menuitem',
            name='category',
            field=models.ManyToManyField(help_text='Choose the menu item stock', to='product.Category', verbose_name='menu item category'),
        ),
    ]
