# Generated by Django 3.2.5 on 2021-08-01 14:08

from django.db import migrations, models
import product.validators


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='max',
            field=models.IntegerField(blank=True, help_text='Enter the max discount price', null=True, validators=[product.validators.price_validator], verbose_name='Max Discount Price'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='percent',
            field=models.FloatField(default=0, help_text='Enter the discount percent', validators=[product.validators.percent_validator], verbose_name='Discount Percent'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='price',
            field=models.IntegerField(default=0, help_text='Enter the discount price', validators=[product.validators.price_validator], verbose_name='Discount Price'),
        ),
    ]
