# Generated by Django 3.2.5 on 2021-08-20 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20210819_1931'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitemvariant',
            name='variable_specifications',
        ),
        migrations.AddField(
            model_name='menuitem',
            name='status',
            field=models.BooleanField(default=False, help_text='has variant?', verbose_name='variant status'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='variable_specification_name',
            field=models.CharField(blank=True, help_text='variable specification name', max_length=30, null=True, verbose_name='Variable Specification name'),
        ),
        migrations.AddField(
            model_name='menuitemvariant',
            name='variable_specification_value',
            field=models.CharField(default='Not entered', help_text='variable specification value', max_length=30, verbose_name='Variable Specification Value'),
        ),
    ]
