# Generated by Django 3.2.5 on 2021-08-02 04:20

from django.db import migrations, models
import django.db.models.deletion
import product.validators


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20210801_1838'),
    ]

    operations = [
        migrations.CreateModel(
            name='OffCode',
            fields=[
                ('discount_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='product.discount')),
                ('code', models.CharField(help_text='Enter the off code', max_length=14, validators=[product.validators.off_code_validator], verbose_name='Off Code')),
            ],
            options={
                'abstract': False,
            },
            bases=('product.discount',),
        ),
    ]
