# Generated by Django 3.2.5 on 2021-08-21 07:34

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('product', '0004_alter_menuitem_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='for similar product', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Similar specification'),
        ),
    ]
