# Generated by Django 3.2.5 on 2021-08-02 12:49

from django.db import migrations, models
import django.db.models.deletion
import product.validators


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_offcode'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delete_time_stamp', models.DateTimeField(blank=True, default=None, help_text='Time of delete', null=True, verbose_name='Deleted Time Stamp')),
                ('is_deleted', models.BooleanField(default=False, help_text='Is delete or not?', verbose_name='Is Deleted')),
                ('create_time_stamp', models.DateTimeField(auto_now_add=True, help_text='Time of create', verbose_name='Create Time Stamp')),
                ('modify_time_stamp', models.DateTimeField(auto_now=True, help_text='Time of modify', verbose_name='Modify Time Stamp')),
                ('name', models.CharField(help_text='Enter the brand name', max_length=30, validators=[product.validators.menu_item_name_validator], verbose_name='brand name')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delete_time_stamp', models.DateTimeField(blank=True, default=None, help_text='Time of delete', null=True, verbose_name='Deleted Time Stamp')),
                ('is_deleted', models.BooleanField(default=False, help_text='Is delete or not?', verbose_name='Is Deleted')),
                ('create_time_stamp', models.DateTimeField(auto_now_add=True, help_text='Time of create', verbose_name='Create Time Stamp')),
                ('modify_time_stamp', models.DateTimeField(auto_now=True, help_text='Time of modify', verbose_name='Modify Time Stamp')),
                ('name', models.CharField(help_text='Enter the Menu items name', max_length=30, validators=[product.validators.menu_item_name_validator], verbose_name='menu item name')),
                ('description', models.TextField(blank=True, help_text='Enter the menu item description', null=True, verbose_name='menu item description')),
                ('brand', models.ForeignKey(blank=True, help_text='Choose the menu item brand', null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.brand', verbose_name='menu item brand')),
                ('category', models.ForeignKey(help_text='Choose the menu item stock', on_delete=django.db.models.deletion.CASCADE, to='product.category', verbose_name='menu item category')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Specification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delete_time_stamp', models.DateTimeField(blank=True, default=None, help_text='Time of delete', null=True, verbose_name='Deleted Time Stamp')),
                ('is_deleted', models.BooleanField(default=False, help_text='Is delete or not?', verbose_name='Is Deleted')),
                ('create_time_stamp', models.DateTimeField(auto_now_add=True, help_text='Time of create', verbose_name='Create Time Stamp')),
                ('modify_time_stamp', models.DateTimeField(auto_now=True, help_text='Time of modify', verbose_name='Modify Time Stamp')),
                ('name', models.CharField(help_text='Enter the Specification name', max_length=200, verbose_name='Specification name')),
                ('value', models.CharField(help_text='Enter the Specification value', max_length=200, verbose_name='Specification Value')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VariableSpecification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delete_time_stamp', models.DateTimeField(blank=True, default=None, help_text='Time of delete', null=True, verbose_name='Deleted Time Stamp')),
                ('is_deleted', models.BooleanField(default=False, help_text='Is delete or not?', verbose_name='Is Deleted')),
                ('create_time_stamp', models.DateTimeField(auto_now_add=True, help_text='Time of create', verbose_name='Create Time Stamp')),
                ('modify_time_stamp', models.DateTimeField(auto_now=True, help_text='Time of modify', verbose_name='Modify Time Stamp')),
                ('name', models.CharField(help_text='Enter the Specification name', max_length=200, verbose_name='Specification name')),
                ('value', models.CharField(help_text='Enter the Specification value', max_length=200, verbose_name='Specification Value')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MenuItemVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delete_time_stamp', models.DateTimeField(blank=True, default=None, help_text='Time of delete', null=True, verbose_name='Deleted Time Stamp')),
                ('is_deleted', models.BooleanField(default=False, help_text='Is delete or not?', verbose_name='Is Deleted')),
                ('create_time_stamp', models.DateTimeField(auto_now_add=True, help_text='Time of create', verbose_name='Create Time Stamp')),
                ('modify_time_stamp', models.DateTimeField(auto_now=True, help_text='Time of modify', verbose_name='Modify Time Stamp')),
                ('price', models.IntegerField(help_text='Enter the menu item price', validators=[product.validators.price_validator], verbose_name='menu item price')),
                ('count', models.IntegerField(default=0, help_text='Enter the menu item stock', validators=[product.validators.price_validator], verbose_name='menu item stock')),
                ('discount', models.ForeignKey(blank=True, help_text='Enter the menu item discount', null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.discount', verbose_name='menu item discount')),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.menuitem')),
                ('variable_specifications', models.ManyToManyField(related_name='variable_specifications', to='product.VariableSpecification')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='menuitem',
            name='specifications',
            field=models.ManyToManyField(related_name='specifications', to='product.Specification'),
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delete_time_stamp', models.DateTimeField(blank=True, default=None, help_text='Time of delete', null=True, verbose_name='Deleted Time Stamp')),
                ('is_deleted', models.BooleanField(default=False, help_text='Is delete or not?', verbose_name='Is Deleted')),
                ('create_time_stamp', models.DateTimeField(auto_now_add=True, help_text='Time of create', verbose_name='Create Time Stamp')),
                ('modify_time_stamp', models.DateTimeField(auto_now=True, help_text='Time of modify', verbose_name='Modify Time Stamp')),
                ('image', models.FileField(help_text='Enter your image', upload_to='product/menu_items/images/', verbose_name='menu item image')),
                ('menu_item', models.ForeignKey(help_text='Enter the menu item for this image', on_delete=django.db.models.deletion.CASCADE, to='product.menuitem', verbose_name='menu item for this image')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
