# Generated by Django 3.2.5 on 2021-08-21 08:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0005_menuitem_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitemvariant',
            name='likes',
            field=models.ManyToManyField(blank=True, null=True, related_name='menu_item_variants_likes', to=settings.AUTH_USER_MODEL, verbose_name='Likes'),
        ),
        migrations.AddField(
            model_name='menuitemvariant',
            name='un_likes',
            field=models.ManyToManyField(blank=True, null=True, related_name='menu_item_variants_un_likes', to=settings.AUTH_USER_MODEL, verbose_name='Un Likes'),
        ),
    ]
