# Generated by Django 3.2.5 on 2021-08-02 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_auto_20210802_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='specifications',
            field=models.ManyToManyField(related_name='menu_items', to='product.Specification'),
        ),
        migrations.AlterField(
            model_name='menuitemvariant',
            name='variable_specifications',
            field=models.ManyToManyField(related_name='menu_item_variants', to='product.VariableSpecification'),
        ),
    ]
