# Generated by Django 3.2.5 on 2021-08-02 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_auto_20210802_1735'),
    ]

    operations = [
        migrations.AddField(
            model_name='discount',
            name='expire_date_time',
            field=models.DateTimeField(default='2021-01-01', help_text='Enter the expire date', verbose_name='Expire Date'),
            preserve_default=False,
        ),
    ]
