# Generated by Django 3.2.5 on 2021-08-21 10:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0006_auto_20210821_1233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitemvariant',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='menu_item_variants_likes', to=settings.AUTH_USER_MODEL, verbose_name='Likes'),
        ),
        migrations.AlterField(
            model_name='menuitemvariant',
            name='un_likes',
            field=models.ManyToManyField(blank=True, related_name='menu_item_variants_un_likes', to=settings.AUTH_USER_MODEL, verbose_name='Un Likes'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delete_time_stamp', models.DateTimeField(blank=True, default=None, help_text='Time of delete', null=True, verbose_name='Deleted Time Stamp')),
                ('is_deleted', models.BooleanField(default=False, help_text='Is delete or not?', verbose_name='Is Deleted')),
                ('create_time_stamp', models.DateTimeField(auto_now_add=True, help_text='Time of create', verbose_name='Create Time Stamp')),
                ('modify_time_stamp', models.DateTimeField(auto_now=True, help_text='Time of modify', verbose_name='Modify Time Stamp')),
                ('comment', models.TextField(verbose_name='Comment')),
                ('rate', models.PositiveIntegerField(default=1)),
                ('is_reply', models.BooleanField(default=False)),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.menuitem', verbose_name='Product')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment_childes', to='product.comment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
