# Generated by Django 3.2.5 on 2021-08-21 18:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0007_auto_20210821_1519'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='comments_likes', to=settings.AUTH_USER_MODEL, verbose_name='Likes'),
        ),
        migrations.AddField(
            model_name='comment',
            name='un_likes',
            field=models.ManyToManyField(blank=True, related_name='comments_un_likes', to=settings.AUTH_USER_MODEL, verbose_name='Un Likes'),
        ),
    ]
