# Generated by Django 3.2.5 on 2021-08-02 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_discount_expire_date_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='name',
            field=models.CharField(help_text='Enter the brand name', max_length=30, verbose_name='brand name'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='name',
            field=models.CharField(help_text='Enter the Menu items name', max_length=30, verbose_name='menu item name'),
        ),
    ]
