# Generated by Django 3.2.5 on 2021-08-23 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_alter_customer_image'),
        ('product', '0008_auto_20210821_2235'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='favorites_customers',
            field=models.ManyToManyField(blank=True, related_name='favorites', to='customer.Customer'),
        ),
    ]
