# Generated by Django 3.2.5 on 2021-08-24 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_menuitem_favorites_customers'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='sell',
            field=models.IntegerField(default=0, verbose_name='sell count'),
        ),
    ]
