# Generated by Django 3.2.5 on 2021-08-30 10:24

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0011_gallery'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brand',
            options={'verbose_name': 'Brand', 'verbose_name_plural': 'Brands'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': 'Comment', 'verbose_name_plural': 'Comments'},
        ),
        migrations.AlterModelOptions(
            name='discount',
            options={'verbose_name': 'Discount', 'verbose_name_plural': 'Discounts'},
        ),
        migrations.AlterModelOptions(
            name='gallery',
            options={'verbose_name': 'Image Gallery', 'verbose_name_plural': 'Image Galleries'},
        ),
        migrations.AlterModelOptions(
            name='image',
            options={'verbose_name': 'Image', 'verbose_name_plural': 'Images'},
        ),
        migrations.AlterModelOptions(
            name='menuitem',
            options={'verbose_name': 'MenuItem', 'verbose_name_plural': 'MenuItems'},
        ),
        migrations.AlterModelOptions(
            name='menuitemvariant',
            options={'verbose_name': 'MenuItemVariant', 'verbose_name_plural': 'MenuItemsVariants'},
        ),
        migrations.AlterModelOptions(
            name='offcode',
            options={'verbose_name': 'OffCode', 'verbose_name_plural': 'OffCodes'},
        ),
        migrations.AlterModelOptions(
            name='specification',
            options={'verbose_name': 'Specification', 'verbose_name_plural': 'Specifications'},
        ),
        migrations.AlterModelOptions(
            name='variablespecification',
            options={'verbose_name': 'VariableSpecification', 'verbose_name_plural': 'VariableSpecifications'},
        ),
        migrations.AddField(
            model_name='brand',
            name='name_fa',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='PersianName'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_fa',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='PersianName'),
        ),
        migrations.AddField(
            model_name='gallery',
            name='description_fa',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Persian description'),
        ),
        migrations.AddField(
            model_name='gallery',
            name='name_fa',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='image persian name'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='description_fa',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='PersianDescription'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='name_fa',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='PersianName'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='variable_specification_name_fa',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Variable Specification persian name'),
        ),
        migrations.AddField(
            model_name='menuitemvariant',
            name='variable_specification_value_fa',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Variable Specification persian Value'),
        ),
        migrations.AddField(
            model_name='specification',
            name='name_fa',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='PersianName'),
        ),
        migrations.AddField(
            model_name='specification',
            name='value_fa',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='PersianValue'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='is_reply',
            field=models.BooleanField(default=False, verbose_name='is reply?'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='name',
            field=models.CharField(help_text='Enter the Menu items name', max_length=50, verbose_name='menu item name'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='variable_specification_name',
            field=models.CharField(blank=True, help_text='variable specification name', max_length=50, null=True, verbose_name='Variable Specification name'),
        ),
        migrations.AlterField(
            model_name='menuitemvariant',
            name='un_likes',
            field=models.ManyToManyField(blank=True, related_name='menu_item_variants_un_likes', to=settings.AUTH_USER_MODEL, verbose_name='DisLikes'),
        ),
        migrations.AlterField(
            model_name='menuitemvariant',
            name='variable_specification_value',
            field=models.CharField(default='Not entered', help_text='variable specification value', max_length=50, verbose_name='Variable Specification Value'),
        ),
    ]
