# Generated by Django 3.2.5 on 2021-08-13 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
        ('customer', '0002_rename_state_address_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delete_time_stamp', models.DateTimeField(blank=True, default=None, help_text='Time of delete', null=True, verbose_name='Deleted Time Stamp')),
                ('is_deleted', models.BooleanField(default=False, help_text='Is delete or not?', verbose_name='Is Deleted')),
                ('create_time_stamp', models.DateTimeField(auto_now_add=True, help_text='Time of create', verbose_name='Create Time Stamp')),
                ('modify_time_stamp', models.DateTimeField(auto_now=True, help_text='Time of modify', verbose_name='Modify Time Stamp')),
                ('status', models.CharField(choices=[('d', 'during'), ('p', 'paid'), ('c', 'canceled')], default='d', help_text='Status for this order', max_length=10, verbose_name='Status')),
                ('customer', models.ForeignKey(help_text='customer for this order', on_delete=django.db.models.deletion.CASCADE, to='customer.customer', verbose_name='Customer')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OrderMenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delete_time_stamp', models.DateTimeField(blank=True, default=None, help_text='Time of delete', null=True, verbose_name='Deleted Time Stamp')),
                ('is_deleted', models.BooleanField(default=False, help_text='Is delete or not?', verbose_name='Is Deleted')),
                ('create_time_stamp', models.DateTimeField(auto_now_add=True, help_text='Time of create', verbose_name='Create Time Stamp')),
                ('modify_time_stamp', models.DateTimeField(auto_now=True, help_text='Time of modify', verbose_name='Modify Time Stamp')),
                ('quantity', models.IntegerField(help_text='quantity', verbose_name='Quantity')),
                ('menu_item_variant', models.ForeignKey(help_text='menu item', on_delete=django.db.models.deletion.CASCADE, to='product.menuitemvariant', verbose_name='Menu Item')),
                ('order', models.ForeignKey(help_text='order', on_delete=django.db.models.deletion.CASCADE, to='order.order', verbose_name='Order')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='order',
            name='menu_item_variants',
            field=models.ManyToManyField(through='order.OrderMenuItem', to='product.MenuItemVariant'),
        ),
        migrations.AddField(
            model_name='order',
            name='off_code',
            field=models.ForeignKey(blank=True, help_text='Off code for this order', null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.offcode', verbose_name='Off Code'),
        ),
    ]
