# Generated by Django 3.2.5 on 2021-08-23 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_alter_ordermenuitem_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('d', 'during'), ('cr', 'creating'), ('p', 'paid'), ('c', 'canceled')], default='d', help_text='Status for this order', max_length=10, verbose_name='Status'),
        ),
    ]
