# Generated by Django 3.2.5 on 2021-08-30 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_auto_20210823_1611'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Order', 'verbose_name_plural': 'Orders'},
        ),
        migrations.AlterModelOptions(
            name='ordermenuitem',
            options={'verbose_name': 'OrderMenuItem', 'verbose_name_plural': 'OrderMenuItems'},
        ),
    ]
